[project]
name = "svasthya"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "googletrans>=4.0.2",
    "groq>=0.14.0",
    "streamlit>=1.41.1",
]
